[SC-97] Moving Files from dss-test
marsfoundation/xchain-helpers pull request #1
Opened 2023-08-24 15:54 UTC by hexonaut

Moving the cross-chain stuff from https://github.com/makerdao/dss-test/tree/master/src .

Domain = Chain. Initial support for Optimism and Arbitrum.

2023-08-29 12:32 UTC, barrutko approved these changes
I'd consider renaming `domain` to `chain`, as it's more of an obvious and self-explanatory name for what it does.
Other than that LGTM.

2023-08-30 23:21 UTC, lucas-manuel requested changes
Small changes

2023-08-31 00:34 UTC, hexonaut commented on src/ArbitrumDomain.sol
> +    InboxLike public INBOX;
It cannot because of the `if` conditional.

2023-08-31 00:35 UTC, hexonaut commented on src/ArbitrumDomain.sol
> +    bytes32 private constant SEND_TO_L1_TOPIC = keccak256("SendTxToL1(address,address,bytes)");
Fixed.

2023-08-31 00:35 UTC, hexonaut commented on src/OptimismDomain.sol
> +    MessengerLike public L1_MESSENGER;
Also cannot. Try it yourself.

2023-08-31 00:40 UTC, lucas-manuel approved these changes

2023-08-31 05:36 UTC, barrutko approved these changes

2023-08-31 05:39 UTC, merged