[SC-425] Adding Circle CCTP support
marsfoundation/xchain-helpers pull request #15
Opened 2024-05-10 07:21 UTC by hexonaut

Adding Circle CCTP support. Please note the naming scheme: anything labelled with just "CCTP" means the protocol itself and anything labelled with "CircleCCTP" refers to the instance that Circle controls.

CCTP is a general protocol so in theory it could be used by another operator.

2024-05-10 12:36 UTC, barrutko commented on test/CCTPIntegration.t.sol
> +    }
Polygon and Avalanche are not tested. IMO they should imo be tested or removed from the list of supported domains.

2024-05-10 12:53 UTC, hexonaut commented on src/CCTPReceiver.sol
> +    address public immutable l1Authority;
I think I prefer the way it is. It matches the Gnosis Receiver / constructor ordering.

2024-05-10 13:02 UTC, hexonaut commented on test/CCTPIntegration.t.sol
> +    }
done, avalanche is missing private rpc key, but we will see if the default is good enough

2024-05-13 19:04 UTC, lucas-manuel reviewed
Lets have a discussion on naming for this, logic is looking good though

2024-05-14 04:36 UTC, hexonaut commented on src/testing/CircleCCTPDomain.sol
> +    MessengerLike public constant L1_MESSENGER = MessengerLike(0x0a992d191DEeC32aFe36203Ad87D7d289a738F81);
So this library is built specifically anchored around Ethereum as always being the L1. L2 to L2 can be done in CCTP, but the structure of this doesn't really support that - nor is it needed at this time at least.

I agree we are stretching the language a bit here, but want to avoid a big restructuring if there is no use case. L2 to L2 will be done by users, but at least for now will not be done by Spark.

Your point is taken though technically there is no problem generalizing this to be source and destination here along with arbitrary host domain so why not.

2024-05-14 04:42 UTC, hexonaut commented on src/testing/CircleCCTPDomain.sol
> +    MessengerLike public constant L1_MESSENGER = MessengerLike(0x0a992d191DEeC32aFe36203Ad87D7d289a738F81);
done

2024-05-14 04:42 UTC, hexonaut commented on src/testing/CircleCCTPDomain.sol
> +            L2_MESSENGER = MessengerLike(0x8186359aF5F57FbB40c6b14A588d2A59C0C29880);
Yes

2024-05-14 04:47 UTC, hexonaut commented on test/CCTPIntegration.t.sol
> +        uint32 hostDomain = 0;  // Ethereum
done

2024-05-14 04:49 UTC, hexonaut commented on src/XChainForwarders.sol
> +        address l1CrossDomain,
done

2024-05-14 04:50 UTC, hexonaut commented on test/CCTPIntegration.t.sol
> +        vm.startPrank(l1Authority);
yeah fair, fixed

2024-05-16 12:35 UTC, barrutko reviewed
I'd go a step further in changing the naming from host/bridged to source/destination and only kept `relayFromHost` and `relayToHost` for compatibility reasons

2024-05-16 12:35 UTC, barrutko commented on src/testing/CircleCCTPDomain.sol
> +    uint256 internal lastToHostLogIndex;
If we are using source/destination naming now, maybe these should be `lastFromSourceLogIndex` and `lastToSourceLogIndex`

2024-05-16 12:35 UTC, barrutko commented on src/testing/CircleCCTPDomain.sol
> +    constructor(StdChains.Chain memory _chain, Domain _hostDomain) Domain(_chain) BridgedDomain(_hostDomain) {
```suggestion
    constructor(StdChains.Chain memory _chain, Domain _sourceDomain) Domain(_chain) BridgedDomain(_sourceDomain) {
```

2024-05-16 12:35 UTC, barrutko commented on test/CCTPIntegration.t.sol
> +        address _l2CrossDomain,
```suggestion
        address _destinationCrossDomain,
```
or even `_destinationCrossDomainMessenger`

2024-05-16 12:35 UTC, barrutko commented on test/CCTPIntegration.t.sol
> +    address l2Authority = makeAddr("l2Authority");
l2 -> destination

2024-05-16 12:35 UTC, barrutko commented on test/CCTPIntegration.t.sol
> +        // Queue up some L2 -> L1 messages
Here again, I'd give up L1/L2 naming and go for source / destination

2024-05-16 14:36 UTC, lucas-manuel requested changes

2024-05-16 14:36 UTC, lucas-manuel commented on src/testing/CircleCCTPDomain.sol
> +        DESTINATION_MESSENGER = MessengerLike(_getMessengerFromChainAlias(_chain.chainAlias));
Align

2024-05-16 14:36 UTC, lucas-manuel commented on src/CCTPReceiver.sol
> +    address public immutable destinationCrossDomain;
Yeah destinationMessenger would be good to consolidate naming

2024-05-16 14:36 UTC, lucas-manuel commented on src/CCTPReceiver.sol
> +    address public immutable sourceAuthority;
```suggestion
    address public immutable destinationCrossDomain;
    uint32  public immutable sourceDomainId;
    address public immutable sourceAuthority;
```

2024-05-16 14:36 UTC, lucas-manuel commented on src/XChainForwarders.sol
> +        address sourceCrossDomain,
sourceMessenger maybe?

2024-05-17 08:30 UTC, hexonaut commented on src/CCTPReceiver.sol
> +    address public immutable destinationCrossDomain;
changed

2024-05-17 08:31 UTC, hexonaut commented on src/testing/CircleCCTPDomain.sol
> +    uint256 internal lastToHostLogIndex;
We still have to match the structure of the interface which contains the host/guest language.

2024-05-17 08:33 UTC, hexonaut commented on test/CCTPIntegration.t.sol
> +        address _l2CrossDomain,
fixed

2024-05-17 08:35 UTC, hexonaut commented on test/CCTPIntegration.t.sol
> +    address l2Authority = makeAddr("l2Authority");
It's not perfect, but we are still testing Ethereum (L1) to some other chain (L2). I think it's more confusing to do source/destination here as the bridge is bi-directional.

2024-05-17 08:35 UTC, hexonaut commented on test/CCTPIntegration.t.sol
> +        // Queue up some L2 -> L1 messages
Same as last comment.

2024-05-17 08:36 UTC, hexonaut commented on src/testing/CircleCCTPDomain.sol
> +        DESTINATION_MESSENGER = MessengerLike(_getMessengerFromChainAlias(_chain.chainAlias));
fixed

2024-05-17 08:36 UTC, hexonaut commented on src/CCTPReceiver.sol
> +    address public immutable sourceAuthority;
fixed

2024-05-17 08:37 UTC, hexonaut commented on src/XChainForwarders.sol
> +        address sourceCrossDomain,
changed

2024-05-17 08:45 UTC, hexonaut commented
Guys regarding the L1/L2 thing, I've added a new task to refactor this repo and generalize it to a multi-bridge world. CCTP is the first case where we are not using a "canonical bridge", but this trend will probably continue and there are now cases where we need to bridge L2 to L1 such as the allocator module which needs to bridge L2 USDC back to Ethereum. It makes sense to refactor this repo and drop the adherence to L1/L2, domains being attached to 1 particular bridge, etc. So let's merge this in and the refactor can be addressed in a new PR.

2024-05-17 17:28 UTC, lucas-manuel approved these changes

2024-05-20 09:08 UTC, barrutko approved these changes

2024-05-20 09:10 UTC, merged