[SC-440] Refactor E2E
marsfoundation/xchain-helpers pull request #16
Opened 2024-05-20 08:08 UTC by hexonaut

Refactoring the E2E cross-domain testing to be generalized. In particular:

 * Split out Bridging from Domains - Domain = blockchain (IE Ethereum, Optimism, Solana, etc), Bridge = Optimism Native Bridge, Circle CCTP, etc
 * Don't assume anchoring on Ethereum
 * Drop the L1/L2 language it should just be source and destination domains

2024-06-04 18:06 UTC, lucas-manuel requested changes
Definitely want to see @barrutko's review on this but this looks good to me as is, I reviewed:
- Testing file diffs (minor changes)
- DomainHelpers
- Bridge

Then I diffed src/test/bridges/* against their *Domain.sol counterparts that were removed as part of this PR. Changes all made sense to me and tests all pass so LGTM after this small change.

2024-06-05 05:44 UTC, hexonaut commented on src/testing/bridges/ArbitrumBridgeTesting.sol
> +import {console} from "./../../../lib/forge-std/src/console.sol";
fixed

2024-06-05 17:02 UTC, lucas-manuel approved these changes

2024-06-06 17:38 UTC, barrutko approved these changes

2024-06-07 09:03 UTC, merged