[SC-437] Fixing coverage by adding unit tests
marsfoundation/xchain-helpers pull request #18
Opened 2024-06-05 09:00 UTC by hexonaut

Adding unit tests to the receiver contracts for more robust testing and it fixes coverage issues.

2024-06-11 12:48 UTC, barrutko requested changes
Two small suggestions, other that that looks good.

2024-06-11 12:48 UTC, barrutko commented on test/mocks/TargetContractMock.sol
> +    uint256 public data;
I'd rename `uint256 public data;` to `counter` or `callCount`.

It'd make tests like this cleaner
```
        assertEq(target.callCount(), 0);
        vm.prank(address(l2CrossDomain));
        TargetContractMock(address(receiver)).someFunc();
        assertEq(target.callCount(), 1);
```

2024-06-11 12:48 UTC, barrutko commented on test/mocks/TargetContractMock.sol
> +        revert("error");
I'd change the revert string to sth like `TargetContract/error`. Again it's make it more clear in tests that this is the error coming from the target contract.
```
        vm.prank(address(l2CrossDomain));
        vm.expectRevert("TargetContract/error");
        TargetContractMock(address(receiver)).revertFunc();
```

2024-06-11 19:44 UTC, lucas-manuel requested changes

2024-06-11 19:44 UTC, lucas-manuel commented on test/mocks/TargetContractMock.sol
> +    uint256 public data;
Agree

2024-06-11 19:44 UTC, lucas-manuel commented on test/mocks/TargetContractMock.sol
> +        revert("error");
Agree

2024-06-11 19:44 UTC, lucas-manuel commented on test/CCTPReceiver.t.sol
> +        receiver.handleReceiveMessage(
May as well assert return value here

2024-06-11 19:44 UTC, lucas-manuel commented on test/IntegrationBase.t.sol
> +        // One more message to destination
Don't we want another to source as well to make sure that both relays handle correctly?

2024-06-12 10:10 UTC, hexonaut commented on test/mocks/TargetContractMock.sol
> +    uint256 public data;
fixed

2024-06-12 10:11 UTC, hexonaut commented on test/mocks/TargetContractMock.sol
> +        revert("error");
changed

2024-06-12 10:12 UTC, hexonaut commented on test/CCTPReceiver.t.sol
> +        receiver.handleReceiveMessage(
added

2024-06-12 10:13 UTC, hexonaut commented on test/IntegrationBase.t.sol
> +        // One more message to destination
ya good point, added

2024-06-12 13:34 UTC, lucas-manuel requested changes

2024-06-12 13:34 UTC, lucas-manuel commented on test/CCTPReceiver.t.sol
> +        assertEq(target.count(), 1);
Align

2024-06-12 15:36 UTC, hexonaut commented on test/CCTPReceiver.t.sol
> +        assertEq(target.count(), 1);
done

2024-06-12 15:40 UTC, barrutko approved these changes
LGTM

2024-06-12 15:57 UTC, lucas-manuel approved these changes

2024-06-12 16:16 UTC, merged