[SC-166] Add generic xchain forwarders library
marsfoundation/xchain-helpers pull request #4
Opened 2023-10-05 09:26 UTC by hexonaut

Smooth over the complexities of bridging with this unified library.

Blocked on Gnosis Chain PR.

2023-10-05 13:45 UTC, hexonaut commented
Ready for review.

2023-10-06 04:27 UTC, barrutko approved these changes

2023-10-06 10:13 UTC, lucas-manuel requested changes

2023-10-06 10:13 UTC, lucas-manuel commented on src/XChainForwarders.sol
> +            0x25ace71c97B33Cc4729CF772ae268934F7ab5fA1,
Can we make these all constants at the top?

2023-10-06 10:13 UTC, lucas-manuel commented on src/XChainForwarders.sol
> +        address l1CrossDomain,
This name wasn't immediately clear to me, maybe something to indicate its an AMB? `l1CrossDomainAMB`?

2023-10-06 10:28 UTC, lucas-manuel requested changes
Constants

2023-10-06 10:29 UTC, lucas-manuel approved these changes

2023-10-09 08:36 UTC, merged