[SC-187] Add Generic Receivers
marsfoundation/xchain-helpers pull request #5
Opened 2023-10-13 13:09 UTC by hexonaut

2023-10-13 14:31 UTC, barrutko reviewed
Generally looks good, but I'd change a few things:
1. Add an L1 message sender getter to the Receiver in case a contract that inherits the Receiver needs the L1 message sender for other purposes than just authorisation.
2. I wouldn't name all of the messenger interfaces the same (`ICrossDomain `). If they'll need to be imported somewhere, it'll get pretty messy.
3. I'd split `Integration.t.sol` into files specific to the 3 domains that we maintain and a file with base stuff. It grew pretty big at this point.

2023-10-13 16:31 UTC, hexonaut commented
Updated.

2023-10-23 08:05 UTC, barrutko submitted a review, later dismissed
LGTM

2023-10-23 16:51 UTC, lucas-manuel requested changes

2023-10-23 16:51 UTC, lucas-manuel commented on test/ArbitrumIntegration.t.sol
> +        messages.push(messageId);
Not a huge deal but probs better to do `super.push(messageId)` here for all since its just modifier that changes

2023-10-23 16:51 UTC, lucas-manuel commented on src/ArbitrumReceiver.sol
> +            require(_getL1MessageSender() == l1Authority);
Do we want an error messag here?

2023-10-23 16:51 UTC, lucas-manuel commented on src/GnosisReceiver.sol
> +        require(_getL1MessageSender() == l1Authority);
Do we want an error messag here?

2023-10-23 16:51 UTC, lucas-manuel commented on src/OptimismReceiver.sol
> +    }
Do we want an error messag here?

2023-10-23 16:58 UTC, hexonaut commented on test/ArbitrumIntegration.t.sol
> +        messages.push(messageId);
done

2023-10-23 17:14 UTC, hexonaut commented on src/ArbitrumReceiver.sol
> +            require(_getL1MessageSender() == l1Authority);
added an error

2023-10-23 17:14 UTC, hexonaut commented on src/OptimismReceiver.sol
> +    }
added an error

2023-10-23 17:15 UTC, hexonaut commented
Note I fixed a bug with the arbitrum receiver being a checked subtraction.

2023-10-23 20:39 UTC, lucas-manuel requested changes

2023-10-23 20:39 UTC, lucas-manuel commented on src/OptimismReceiver.sol
> +    }
```suggestion
        require(msg.sender == address(l2CrossDomain), "Receiver/invalid-domain");
        require(_getL1MessageSender() == l1Authority, "Receiver/invalid-sender");
```

2023-10-23 20:39 UTC, lucas-manuel commented on src/ArbitrumReceiver.sol
> +    }
```suggestion
        require(_getL1MessageSender() == l1Authority, "Receiver/invalid-sender");
```

2023-10-23 20:39 UTC, lucas-manuel commented on src/GnosisReceiver.sol
> +    }
```suggestion
        require(msg.sender == address(l2CrossDomain),            "Receiver/invalid-domain");
        require(l2CrossDomain.messageSourceChainId() == chainId, "Receiver/invalid-chainid");
        require(_getL1MessageSender() == l1Authority,            "Receiver/invalid-sender");
    }
```

2023-10-23 20:40 UTC, lucas-manuel requested changes
Suggested changes since we'll want to see error reason

2023-10-23 20:40 UTC, lucas-manuel requested changes
Suggested changes since we'll want to see error reason

2023-10-24 14:46 UTC, hexonaut commented on src/OptimismReceiver.sol
> +    }
fixed

2023-10-24 14:46 UTC, hexonaut commented on src/ArbitrumReceiver.sol
> +    }
fixed

2023-10-24 14:47 UTC, hexonaut commented on src/GnosisReceiver.sol
> +    }
fixed

2023-10-24 15:53 UTC, hexonaut commented
I've added more extensive testing for the failure modes for better coverage.

2023-10-24 17:03 UTC, lucas-manuel requested changes

2023-10-24 17:03 UTC, lucas-manuel commented on src/testing/ArbitrumDomain.sol
> +                        revert(add(response,32),mload(response))
Space after comma

2023-10-24 17:03 UTC, lucas-manuel commented on src/testing/ArbitrumDomain.sol
> +                        revert(add(response,32),mload(response))
Spaces after commas

2023-10-24 17:03 UTC, lucas-manuel commented on src/testing/OptimismDomain.sol
> +                        revert(add(response,32),mload(response))
Spaces after commas

2023-10-24 17:07 UTC, hexonaut commented on src/testing/ArbitrumDomain.sol
> +                        revert(add(response,32),mload(response))
done

2023-10-24 17:07 UTC, hexonaut commented on src/testing/ArbitrumDomain.sol
> +                        revert(add(response,32),mload(response))
done

2023-10-24 17:07 UTC, hexonaut commented on src/testing/OptimismDomain.sol
> +                        revert(add(response,32),mload(response))
done

2023-10-24 17:10 UTC, lucas-manuel approved these changes

2023-10-26 12:07 UTC, barrutko approved these changes

2023-10-26 12:08 UTC, merged