[SC-164] Add Polygon zkEVM
marsfoundation/xchain-helpers pull request #8
Opened 2023-10-26 15:41 UTC by barrutko

The Receiver contract is still missing

2023-10-26 17:20 UTC, hexonaut requested changes
Some minor changes. This also lacks the receiver authentication, which needs to be added in a subsequent PR.

2023-10-26 17:20 UTC, hexonaut commented on src/testing/ZkEVMDomain.sol
> +        require(_isBridgeMessageEvent(log, host), "ZkEVMDomain: !bridgeMessage");
This check is redundant.

2023-10-26 17:20 UTC, hexonaut commented on src/testing/ZkEVMDomain.sol
> +            revert MessageFailed();
This should propagate the actual revert message similar to other domains.

2023-10-27 11:01 UTC, hexonaut approved these changes

2023-10-27 13:29 UTC, hexonaut commented on src/XChainForwarders.sol
> +        uint32 destinationNetworkId,
This should be defaulted. I think it's `1` for the rollup.

2023-10-27 13:29 UTC, hexonaut commented on src/XChainForwarders.sol
> +        bool forceUpdateGlobalExitRoot,
This should be defaulted. Figure out what the default value should be.

2023-10-27 14:25 UTC, lucas-manuel requested changes

2023-10-27 14:25 UTC, lucas-manuel commented on test/ZkEVMIntegration.sol
> +contract ZkEVMIntegrationTest is IntegrationBaseTest {
This filename needs `.t.sol` at end of it

2023-10-27 14:25 UTC, lucas-manuel commented on test/ZkEVMIntegration.sol
> +        // Queue up two more L1 -> L2 messages
L2 -> L1

2023-10-27 14:26 UTC, lucas-manuel requested changes
Checked forwarders and domain code against PR, LGTM, some changes

2023-10-27 14:26 UTC, lucas-manuel requested changes
Checked forwarders and domain code against PR, LGTM, some changes

2023-10-27 14:38 UTC, hexonaut approved these changes
LGTM now after Lucas's changes.

2023-10-27 14:59 UTC, lucas-manuel commented on src/testing/ZkEVMDomain.sol
> +import { StdChains } from "forge-std/StdChains.sol";
Resolving as will be changed in new PR

2023-10-27 14:59 UTC, lucas-manuel approved these changes
LGTM

2023-10-27 15:11 UTC, hexonaut approved these changes

2023-10-27 15:14 UTC, merged